const questions = {
  1: [
    {
      question: 'With which sport is David Beckham associated?',
      category: 'Sport & Leisure',
      difficulty: 1,
      allAnswers: ['Hockey', 'Tennis', 'Football', 'Surfing'],
      corrAnsIndex: 2,
    },
    {
      category: 'Geography',
      question: 'Which of these countries borders Portugal?',
      difficulty: 1,
      allAnswers: ['Morocco', 'Andorra', 'France', 'Spain'],
      corrAnsIndex: 3,
    },
    {
      question: 'In the Marvel Cinematic Unvierse, which character is played by Scarlett Johansson?',
      category: 'Film & TV',
      difficulty: 1,
      allAnswers: ['Black Widow', 'Gamora', 'Valkyrie', 'Captain Marvel'],
      corrAnsIndex: 0,
    },
    {
      question: 'Which of these cities is in Cuba?',
      category: 'Geography',
      difficulty: 1,
      allAnswers: ['San Salvador', 'Havana', 'Santiago', 'Guatemala City'],
      corrAnsIndex: 1,
    },
    {
      question: 'Which Of The Worlds Continents Has The Highest Population?',
      category: 'Geography',
      difficulty: 1,
      allAnswers: ['North America', 'Europe', 'Africa', 'Asia'],
      corrAnsIndex: 3,
    },
  ],
  2: [
    {
      question: 'Which of these cities is in Denmark?',
      category: 'Geography',
      difficulty: 2,
      allAnswers: ['Copenhagen', 'Athens', 'Munich', 'Milan'],
      corrAnsIndex: 0,
    },
    {
      question: 'What Name Was Given To The Period From 1919 To 1933 When Alcohol Was Banned In The USA?',
      category: 'History',
      difficulty: 2,
      allAnswers: ['The Dry Spell', 'The Prohibition', 'The Dark Days', 'The Moonshine'],
      corrAnsIndex: 1,
    },
    {
      question: 'Who was the 1st president of the USA,',
      category: 'History',
      difficulty: 2,
      allAnswers: ['Chester Arthur', 'Ulysses S. Grant', 'Millard Fillmore', 'George Washington'],
      corrAnsIndex: 3,
    },
    {
      question: 'What is Cosmology the study of?',
      category: 'Science',
      difficulty: 2,
      allAnswers: ['the cosmos or our place in it', 'beetles', 'flags', 'study of the mouth and its diseases'],
      corrAnsIndex: 0,
    },
    {
      question: 'Where in the world would you most expect to be served a taco?',
      category: 'Food & Drink',
      difficulty: 2,
      allAnswers: ['Mexico', 'Japan', 'Brazil', 'Bhutan'],
      corrAnsIndex: 0,
    },
  ],
  3: [
    {
      question: 'What is the mathematical term used to describe the shape of a cell in a honeycomb? ',
      category: 'Science',
      difficulty: 3,
      allAnswers: ['Octagon', 'Dodecahedron', 'Hexagon', 'Pentagon'],
      corrAnsIndex: 2,
    },
    {
      question: 'After whom was America named?',
      category: 'General Knowledge',
      difficulty: 3,
      allAnswers: ['Aymeric Santiago', 'Merica Bonnuci', 'Amir Icarlo', 'Amerigo Vespucci'],
      corrAnsIndex: 3,
    },
    {
      question: 'Which of these countries borders Mongolia?',
      category: 'Geography',
      difficulty: 3,
      allAnswers: ['Bhutan', 'North Korea', 'Russia', 'Myanmar'],
      corrAnsIndex: 2,
    },
    {
      question: 'What is Nanotechnology the study of?',
      category: 'Science',
      difficulty: 3,
      allAnswers: [
        'things in order of time or time',
        'movement in relation to human anatomy; a branch of medicine',
        'wine',
        'the study and design of machines at the molecular level',
      ],
      corrAnsIndex: 3,
    },
    {
      question: 'Mark Ruffalo plays the role of which character in the Marvel Cinematic Unvierse?',
      category: 'Film & TV',
      difficulty: 3,
      allAnswers: ['Karl Mordo', 'Dr. Bruce Banner', 'Odin', 'Ned Leeds'],
      corrAnsIndex: 1,
    },
  ],
  4: [
    {
      question: "Which philosopher famously said 'The only thing I know is that I know nothing'?",
      category: 'Society & Culture',
      difficulty: 4,
      allAnswers: ['Socrates', 'Bertrand Russell', 'Immanuel Kant', 'Thomas Hobbes'],
      corrAnsIndex: 0,
    },
    {
      question: 'What happened on the 21st July 1969?',
      category: 'History',
      difficulty: 4,
      allAnswers: [
        'The Internet was invented',
        'World War 2 ended',
        'John F Kennedy was assassinated',
        'First Manned moon landing',
      ],
      corrAnsIndex: 3,
    },
    {
      question: 'Which of these colors would you find on the flag of Indonesia?',
      category: 'Geography',
      difficulty: 4,
      allAnswers: ['Orange', 'Red', 'Green', 'Yellow'],
      corrAnsIndex: 1,
    },
    {
      question: "On May 1st 1931 the world's then tallest building was opened in New York City. Which building was it?",
      category: 'History',
      difficulty: 4,
      allAnswers: ['The Chrysler Building', 'The World Trade Center', 'The Empire State Building', 'The CN Tower'],
      corrAnsIndex: 2,
    },
    {
      question: 'The ancient attempt to transmute base metals into gold was called ________.',
      category: 'Geography',
      difficulty: 4,
      allAnswers: ['Magic', 'Aurentalism', 'Alchemy', 'Mystic Metallurgy'],
      corrAnsIndex: 2,
    },
  ],
  5: [
    {
      question: 'What is the word for a group of pigs?',
      category: 'Science',
      difficulty: 5,
      allAnswers: ['A swarm', 'A flight', 'A watch', 'A litter'],
      corrAnsIndex: 3,
    },
    {
      question: 'What is a male hamster known as?',
      category: 'A Buck',
      difficulty: 5,
      allAnswers: ['A Ram', 'A Buck', 'A Billy', 'A Boar'],
      corrAnsIndex: 1,
    },
    {
      question: 'In which century was The Black Death?',
      category: 'History',
      difficulty: 5,
      allAnswers: ['Twentieth', 'Tenth', 'Fourteenth', 'Seventh'],
      corrAnsIndex: 2,
    },
    {
      question: 'Which artist painted "Three Musicians"',
      category: 'Arts & Literature',
      difficulty: 5,
      allAnswers: ['Henri Matisse', 'Pablo Picasso', 'Sandro Botticelli', 'Georges Seurat'],
      corrAnsIndex: 1,
    },
    {
      question: 'When was the first email sent?',
      category: 'History',
      difficulty: 5,
      allAnswers: ['1957', '1964', '1978', '1971'],
      corrAnsIndex: 3,
    },
  ],
};

export default questions;
